'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'rw'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pharmacy': 'Pharmacy',
    'nav.animalSales': 'Animal Sales',
    'nav.feeds': 'Feeds',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.blog': 'Blog',
    'nav.login': 'Login',
    'nav.register': 'Register',
    
    // Common
    'common.backTo': 'Back to',
    'common.loading': 'Loading...',
    'common.notFound': 'Not Found',
    'common.available': 'Available',
    'common.price': 'Price',
    'common.description': 'Description',
    'common.location': 'Location',
    'common.orderNow': 'Order Now',
    'common.addToWishlist': 'Add to Wishlist',
    'common.removeFromWishlist': 'Remove from Wishlist',
    'common.share': 'Share',
    'common.requestDelivery': 'Request Delivery Quote',
    'common.productInfo': 'Product Information',
    'common.inStock': 'In Stock',
    'common.delivery': 'Delivery',
    'common.premium': 'Premium',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.contactUs': 'Contact Us',
    'common.readMore': 'Read More',
    'common.sortBy': 'Sort by',
    'common.filterBy': 'Filter by',
    'common.search': 'Search',
    'common.all': 'All',
    'common.category': 'Category',
    'common.categories': 'Categories',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.message': 'Message',
    'common.submit': 'Submit',
    'common.send': 'Send',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    
    // Home Page
    'home.hero.titleStart': 'Track, Consult, and',
    'home.hero.titleEnd': 'Care for Your Animals',
    'home.hero.subtitle': 'Innovative solutions for livestock and pet owners. Advanced tracking, expert consultations, and comprehensive care - all in one place',
    'home.hero.cta': 'Explore Our Services',
    'home.hero.bookConsultation': 'Book a Consultation',
    'home.hero.trusted': 'Trusted by 5,000+ animal owners across Rwanda',
    'home.services.title': 'Our Featured Services',
    'home.services.subtitle': 'Comprehensive solutions for animal health, tracking, and management to ensure the well-being of your livestock and pets',
    'home.features.title': 'Why Choose NTDM Animal Hospital?',
    'home.features.subtitle': 'Experience the difference with our commitment to excellence, innovation, and comprehensive animal care',
    'home.features.expert.title': 'Expert Veterinarians',
    'home.features.expert.desc': 'Our team of certified veterinarians brings years of experience and specialized knowledge to every case',
    'home.features.technology.title': 'Innovative Technology',
    'home.features.technology.desc': 'We use cutting-edge tracking devices and diagnostic tools to provide the best care for your animals',
    'home.features.comprehensive.title': 'Comprehensive Care',
    'home.features.comprehensive.desc': 'From preventive care to emergency services, we offer a complete range of solutions for all your animal needs',
    'home.testimonials.title': 'What Our Customers Say',
    'home.testimonials.subtitle': 'Don\'t just take our word for it. Here\'s what animal owners across Rwanda have to say about NTDM Animal Hospital',
    'home.testimonials.farmer': 'Livestock Farmer',
    'home.testimonials.petOwner': 'Pet Owner',
    'home.testimonials.poultryFarmer': 'Poultry Farmer',
    'home.testimonials.dairyFarmer': 'Dairy Farmer',
    'home.testimonials.quote1': 'The tracking devices from NTDM have revolutionized how I manage my cattle. I can monitor their location and health status in real-time, which has significantly improved my farm\'s productivity',
    'home.testimonials.quote2': 'The virtual consultations are incredibly convenient. When my dog was sick, I got expert advice within minutes without having to travel to the clinic. Highly recommend!',
    'home.testimonials.quote3': 'The disease monitoring system helped me detect an outbreak early in my poultry farm. The quick response from NTDM\'s veterinarians saved most of my flock. Their service is invaluable',
    'home.testimonials.quote4': 'I purchased my dairy cows through NTDM\'s marketplace and received healthy, high-yielding animals. Their follow-up care and support has been exceptional. My dairy production has increased by 30%!',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.subtitle': 'Contact us today for professional animal healthcare services',
    'home.locations.title': 'Our Locations',
    'home.locations.subtitle': 'Visit us at any of our convenient locations across Rwanda. Each clinic offers our full range of animal healthcare services',
    'home.locations.directions': 'Get Directions',
    // Portal Section
    'home.portal.title': 'Customer Portal',
    'home.portal.subtitle': 'Our comprehensive customer portal gives you complete control over your animals\' health and management. Track, consult, and care for your animals effortlessly',
    'home.portal.management.title': 'Animal Management',
    'home.portal.management.desc': 'Register and track all your animals in one place with detailed health records and location data',
    'home.portal.consultations.title': 'Veterinary Consultations',
    'home.portal.consultations.desc': 'Book and manage virtual consultations with our expert veterinarians from anywhere',
    'home.portal.alerts.title': 'Real-time Alerts',
    'home.portal.alerts.desc': 'Receive instant notifications about your animals\' health, location changes, or appointment reminders',
    'home.portal.records.title': 'Health Records',
    'home.portal.records.desc': 'Access complete medical history, prescriptions, and treatment plans for all your registered animals',
    'home.portal.login': 'Login to Portal',
    'home.portal.createAccount': 'Create Account',
    'home.portal.trackTitle': 'Track Your Animals Anywhere',
    'home.portal.trackDesc': 'Access real-time data and health information from your phone or computer',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive animal healthcare and management solutions',
    'services.tracking.title': 'Animal Tracking',
    'services.tracking.desc': 'Advanced GPS tracking devices for livestock monitoring',
    'services.consultation.title': 'Veterinary Consultation',
    'services.consultation.desc': 'Professional veterinary advice and treatment',
    'services.monitoring.title': 'Disease Monitoring',
    'services.monitoring.desc': 'Early detection and prevention of animal diseases',
    
    // Pharmacy
    'pharmacy.title': 'Veterinary Pharmacy',
    'pharmacy.subtitle': 'Professional veterinary medicines and healthcare products',
    'pharmacy.notFound': 'Medicine not found',
    'pharmacy.notFoundDesc': "The medicine you're looking for doesn't exist.",
    'pharmacy.dosage': 'Dosage',
    'pharmacy.sideEffects': 'Side Effects',
    'pharmacy.instructions': 'Instructions',
    'pharmacy.prescription': 'Prescription Required',
    
    // Animal Sales
    'animals.title': 'Quality Livestock',
    'animals.subtitle': 'Healthy animals for farming and breeding',
    'animals.notFound': 'Animal not found',
    'animals.notFoundDesc': "The animal you're looking for doesn't exist.",
    'animals.breed': 'Breed',
    'animals.age': 'Age',
    'animals.weight': 'Weight',
    'animals.health': 'Health Status',
    'animals.vaccination': 'Vaccination',
    'animals.gender': 'Gender',
    
    // Feeds
    'feeds.title': 'Premium Animal Feeds',
    'feeds.subtitle': 'Premium nutrition for healthy, productive animals',
    'feeds.notFound': 'Feed not found',
    'feeds.notFoundDesc': "The feed product you're looking for doesn't exist.",
    'feeds.feedDetails': 'Feed Details',
    'feeds.type': 'Type',
    'feeds.quality': 'Quality',
    'feeds.targetAnimal': 'Target Animal',
    'feeds.package': 'Package',
    'feeds.availability': 'Availability',
    'feeds.status': 'Status',
    'feeds.qualityRating': 'Quality Rating',
    'feeds.nutritionFacts': 'Nutrition Facts',
    'feeds.ingredients': 'Ingredients',
    
    // About
    'about.title': 'About NTDM Animal Hospital',
    'about.subtitle': 'Leading animal healthcare provider in Rwanda',
    'about.mission': 'Our Mission',
    'about.vision': 'Our Vision',
    'about.values': 'Our Values',
    'about.team': 'Our Team',
    'about.history': 'Our History',
    'about.mentor': 'Our Mentors',
    'about.experience': 'Experience the NTDM Difference',
    'about.experienceParagraph': 'We invite you to visit NTDM Animal Hospital and experience our commitment to animal health, innovation, and exceptional service firsthand.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to answer any questions you may have about our services or to book your next consultation',
    'contact.address': 'Address',
    'contact.hours': 'Business Hours',
    'contact.emergency': 'Emergency Contact',
    'contact.form.title': 'Send us a message',
    'contact.form.success': 'Message Sent!',
    'contact.form.error': 'Failed to send message. Please try again.',
    'contact.form.thankYou': 'Thank you for contacting us. We\'ll get back to you as soon as possible',
    'contact.form.sendAnother': 'Send Another Message',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.phonePlaceholder': 'Enter your phone number',
    'contact.form.messagePlaceholder': 'Enter your message',
    'contact.form.sending': 'Sending...',
    'contact.findUs': 'Find Us',
    'contact.getInTouch': 'Get In Touch',
    'common.today': 'Today',
    
    // Footer
    'footer.company': 'NTDM Animal Hospital',
    'footer.description': 'Revolutionizing animal health with innovative tracking, consultation, and care solutions for livestock and pets',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact Info',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved',
    'footer.weekdays': 'Monday - Friday',
    'footer.saturday': 'Saturday',
    'footer.newsletter': 'Subscribe to Our Newsletter',
    'footer.newsletterDesc': 'Stay updated with our latest services, animal care tips, and special offers',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.serving': 'Serving Rwanda and East Africa',
    'footer.tagline': 'Track, Consult, and Care for Your Animals',
    
    // Blog
    'blog.subtitle': 'Expert insights, tips, and news on animal health, tracking, and care from our veterinarians',
    
    // Booking
    'booking.title': 'Book Your Consultation',
    'booking.subtitle': 'Schedule your visit to NTDM Animal Hospital and experience our expert veterinary services',
    
    // Sorting & Filtering
    'sort.newest': 'Newest First',
    'sort.oldest': 'Oldest First',
    'sort.priceHigh': 'Price: High to Low',
    'sort.priceLow': 'Price: Low to High',
    'sort.nameAZ': 'Name: A to Z',
    'sort.nameZA': 'Name: Z to A',
    
    // Quality levels
    'quality.high': 'High Quality',
    'quality.medium': 'Medium Quality',
    'quality.low': 'Low Quality',
    'quality.premium': 'Premium Quality',
    
    // Auth
    'auth.loginDesc': 'Enter your credentials to access your account',
    'auth.password': 'Password',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.loggingIn': 'Logging in...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.registerHere': 'Register here',
    'auth.accountCreated': 'Account Created Successfully!',
    'auth.welcome': 'Welcome to NTDM Animal Hospital',
    'auth.checkEmail': 'Please check your email inbox for a welcome message',
    'auth.checkEmailTitle': 'Check Your Email',
    'auth.continueLogin': 'Continue to Login',
    'auth.createAccount': 'Create an account',
    'auth.createAccountDesc': 'Enter your information to create an account',
    'auth.confirmPassword': 'Confirm Password',
    'auth.accountType': 'Account Type',
    'auth.farmerPetOwner': 'Farmer/Pet Owner',
    'auth.creatingAccount': 'Creating account...',
    'auth.haveAccount': 'Already have an account?',
    'auth.signIn': 'Sign in',
    'auth.welcomeBack': 'Welcome Back to NTDM Animal Hospital',
    'auth.loginWelcomeDesc': 'Log in to access your dashboard, track your animals, and manage your consultations',
    'auth.joinNTDM': 'Join NTDM Animal Hospital',
    'auth.registerWelcomeDesc': 'Create an account to access our services, track your animals, and manage your consultations',
    'auth.sector': 'Sector',
    'auth.district': 'District',
    'auth.orContinueWith': 'OR CONTINUE WITH',
    'auth.phoneNumber': 'Phone Number',

    // Farmer Dashboard
    'farmer.dashboard': 'Farmer Dashboard',
    'farmer.welcomeBack': 'Welcome back',
    'farmer.manageFarm': 'Manage your farm efficiently with our comprehensive tools',
    'farmer.animals': 'Animals',
    'farmer.registered': 'Registered',
    'farmer.pending': 'Pending',
    'farmer.awaiting': 'Awaiting',
    'farmer.accepted': 'Accepted',
    'farmer.confirmed': 'Confirmed',
    'farmer.rejected': 'Rejected',
    'farmer.declined': 'Declined',
    'farmer.registerAnimal': 'Register Animal',
    'farmer.addNewLivestock': 'Add new livestock',
    'farmer.bookConsultation': 'Book Consultation',
    'farmer.scheduleVisit': 'Schedule visit',
    'farmer.viewConsultations': 'View Consultations',
    'farmer.manageBookings': 'Manage bookings',
    'farmer.recentActivity': 'Recent Activity',
    'farmer.items': 'items',
    'farmer.animalRegistered': 'Animal registered',
    'farmer.addedOn': 'Added on',
    'farmer.consultation': 'consultation',
    'farmer.bookedOn': 'Booked on',
    'farmer.noRecentActivity': 'No recent activity',
    'farmer.farmActivitiesAppear': 'Your farm activities will appear here',
    'farmer.portal': 'Farmer Portal',
    'farmer.dashboard': 'Dashboard',
    'farmer.consultations': 'Consultations',
    'farmer.tracking': 'Tracking',
    'farmer.messages': 'Messages',
    'farmer.notifications': 'Notifications',
    'farmer.profile': 'Profile',
    'farmer.settings': 'Settings',
    'farmer.logout': 'Logout',
    'farmer.myAnimals': 'My Animals',
    'farmer.registeredAnimals': 'Registered Animals',
    'farmer.registerNewAnimal': 'Register New Animal',
    'farmer.animalsInventory': 'Animals Inventory',
    'farmer.noAnimalsYet': 'You don\'t have any registered animals yet',
    'farmer.registerAnAnimal': 'Register an Animal',
    'farmer.name': 'Name',
    'farmer.type': 'Type',
    'farmer.breed': 'Breed',
    'farmer.location': 'Location',
    'farmer.status': 'Status',
    'farmer.price': 'Price',
    'farmer.actions': 'Actions',
    'farmer.healthy': 'Healthy',
    'farmer.sick': 'Sick',
    'farmer.underTreatment': 'Under Treatment',
    'farmer.viewDetails': 'View Details',
    'farmer.edit': 'Edit',
    'farmer.myConsultations': 'My Consultations',
    'farmer.newConsultation': 'New Consultation',
    'farmer.consultationHistory': 'Consultation History',
    'farmer.noConsultationsYet': 'You don\'t have any consultations yet',
    'farmer.bookAConsultation': 'Book a Consultation',
    'farmer.service': 'Service',
    'farmer.doctor': 'Doctor',
    'farmer.date': 'Date',
    'farmer.time': 'Time',
    'farmer.delete': 'Delete',
    'farmer.myProfile': 'My Profile',
    'farmer.farmer': 'Farmer',
    'farmer.fullName': 'Full Name',
    'farmer.bio': 'Bio',
    'farmer.animalInformation': 'Animal Information',
    'farmer.enterAnimalName': 'Enter animal name',
    'farmer.animalType': 'Animal Type',
    'farmer.selectAnimalType': 'Select animal type',
    'farmer.cow': 'Cow',
    'farmer.goat': 'Goat',
    'farmer.sheep': 'Sheep',
    'farmer.chicken': 'Chicken',
    'farmer.dog': 'Dog',
    'farmer.cat': 'Cat',
    'farmer.other': 'Other',
    'farmer.enterBreed': 'Enter breed',
    'farmer.class': 'Class',
    'farmer.selectClass': 'Select class',
    'farmer.dairy': 'Dairy',
    'farmer.meat': 'Meat',
    'farmer.poultry': 'Poultry',
    'farmer.pet': 'Pet',
    'farmer.district': 'District',
    'farmer.selectDistrict': 'Select district',
    'farmer.sector': 'Sector',
    'farmer.selectSector': 'Select sector',
    'farmer.ownerName': 'Owner Name',
    'farmer.enterOwnerName': 'Enter owner name',
    'farmer.phoneNumber': 'Phone Number',
    'farmer.enterPhoneNumber': 'Enter phone number',
    'farmer.priceRWF': 'Price (RWF)',
    'farmer.enterPrice': 'Enter price',
    'farmer.cancel': 'Cancel',
    'farmer.registering': 'Registering...',
    'farmer.communicateVeterinarians': 'Communicate with veterinarians about your animals',
    'farmer.searchMessages': 'Search messages...',
    'farmer.startNewConversation': 'Start New Conversation',
    'farmer.noConversationsYet': 'No conversations yet. Start a new chat!',
    'farmer.noMessagesYet': 'No messages yet',
    'farmer.veterinarian': 'Veterinarian',
    'farmer.noMessagesStart': 'No messages yet. Start the conversation!',
    'farmer.typeMessage': 'Type a message...',
    'farmer.selectConversation': 'Select a conversation to start chatting',
    'farmer.cowHealthMonitor': 'Cow Health Monitor',
    'farmer.realTimeTracking': 'Real-time health and location tracking',
    'farmer.lastUpdated': 'Last updated',
    'farmer.exportReport': 'Export Report',
    'farmer.refresh': 'Refresh',
    'farmer.dataSourceConfig': 'Data Source Configuration',
    'farmer.channelId': 'Channel ID',
    'farmer.apiKey': 'API Key',
    'farmer.resultsCount': 'Results Count',
    'farmer.fetch': 'Fetch',
    'farmer.loadingSensorData': 'Loading sensor data...',
    'farmer.noDataAvailable': 'No Data Available',
    'farmer.noSensorData': 'No sensor data found for the selected channel. Please verify the Channel ID and API Key.',
    'farmer.tryAgain': 'Try Again',
    'farmer.dataFieldsMapping': 'Data Fields Mapping',
    'farmer.field': 'Field',
    'farmer.latest': 'Latest',
    'farmer.average': 'Average',
    'farmer.locationCoverage': 'Location Coverage',
    'farmer.healthMetricsTrend': 'Health Metrics Trend',
    'farmer.distribution': 'Distribution',
    'farmer.locationTrackingInRwanda': 'Location Tracking in Rwanda',
    'farmer.recentReadings': 'Recent Readings',
    'farmer.time': 'Time',
    'farmer.status': 'Status',
    'farmer.location': 'Location',
    'farmer.noLocationData': 'No location data',
    'farmer.healthStatusDistribution': 'Health Status Distribution',
    'farmer.bpmRangeDistribution': 'BPM Range Distribution',
    'farmer.noDataAvailableChart': 'No data available',
    'farmer.count': 'Count',
    'farmer.readings': 'readings',
    'farmer.ofTotal': 'of total',
    'farmer.animalHealthMonitoringReport': 'Animal Health Monitoring Report',
    'farmer.animal': 'Animal',
    'farmer.generated': 'Generated',
    'farmer.healthSummary': 'Health Summary',
    'farmer.temperature': 'Temperature',
    'farmer.timestamp': 'Timestamp',
    'farmer.latitude': 'Latitude',
    'farmer.longitude': 'Longitude',
    'farmer.bpmStatus': 'BPM Status',
    'farmer.tempStatus': 'Temp Status',
    'farmer.hasLocation': 'Has Location',
    'farmer.animalInfo': 'Animal Info',
    'farmer.healthData': 'Health Data',
    'farmer.reportDate': 'Report Date',
    'farmer.totalRecords': 'Total Records',
    'farmer.unknown': 'Unknown',
    'farmer.yes': 'Yes',
    'farmer.no': 'No',
    'farmer.noData': 'No Data',
    'farmer.low': 'Low',
    'farmer.normal': 'Normal',
    'farmer.elevated': 'Elevated',
    'farmer.high': 'High',
    'farmer.consultationDetails': 'Consultation Details',
    'farmer.backToAllConsultations': 'Back to All Consultations',
    'farmer.consultationFor': 'Consultation for Vaccination',
    'farmer.acceptedWithFeedback': 'Accepted with feedback',
    'farmer.rejectedWithFeedback': 'Rejected with feedback',
    'farmer.completedWithFeedback': 'Completed with feedback',
    'farmer.fullName': 'Full Name',
    'farmer.unknownDoctor': 'Unknown Doctor',
    'farmer.createdAt': 'Created At',
    'farmer.editConsultation': 'Edit Consultation',
    'farmer.deleteConsultation': 'Delete Consultation',
    'farmer.locationPointsTracked': 'location points tracked',
    'farmer.lastSeen': 'Last seen',
    'farmer.resetView': 'Reset View',
    'farmer.latestLocation': 'Latest Location',
    'farmer.loadingRwandaMap': 'Loading Rwanda map...',
    'farmer.coverageArea': 'Coverage Area',
    'farmer.trackingLocations': 'Tracking locations',
    'farmer.currentHealth': 'Current Health',
    'farmer.heartRate': 'Heart rate',
    'farmer.bodyTemperature': 'Body temperature',
    'farmer.selectedLocationDetails': 'Selected Location Details',
    'farmer.coordinates': 'Coordinates',
    'farmer.multiplePoints': 'Multiple',
    'farmer.singlePoint': 'Single',
    'farmer.noPoints': 'No',
    
    // Animal Details
    'animal.details': 'Animal Details',
    'animal.backToAnimals': 'Back to Animals',
    'animal.breed': 'Breed',
    'animal.class': 'Class',
    'animal.location': 'Location',
    'animal.price': 'Price',
    'animal.owner': 'Owner',
    'animal.phone': 'Phone',
    'animal.registeredOn': 'Registered On',
    'animal.deleteAnimal': 'Delete Animal',
    'animal.editAnimal': 'Edit Animal',
  },
  rw: {
    // Navigation
    'nav.home': 'Ahabanza',
    'nav.services': 'Serivisi',
    'nav.pharmacy': 'Farumasi',
    'nav.animalSales': 'Kugurisha itungo',
    'nav.feeds': 'Indyo z\'itungo',
    'nav.about': 'Ibibazo',
    'nav.contact': 'Twandikire',
    'nav.blog': 'Blog',
    'nav.login': 'Kwinjira',
    'nav.register': 'Kwiyandikisha',
    
    // Common
    'common.backTo': 'Subira ku',
    'common.loading': 'Birashakisha...',
    'common.notFound': 'Ntibibonetse',
    'common.available': 'Birahari',
    'common.price': 'Igiciro',
    'common.description': 'Ibisobanuro',
    'common.location': 'Aho biherereye',
    'common.orderNow': 'Biteganye Ubu',
    'common.addToWishlist': 'Shyira mu Byifuza',
    'common.removeFromWishlist': 'Kuramo mu Byifuza',
    'common.share': 'Sangira',
    'common.requestDelivery': 'Saba Igiciro cyo Gutwarwa',
    'common.productInfo': 'Amakuru y\'Igicuruzwa',
    'common.inStock': 'Birahari',
    'common.delivery': 'Gutwarwa',
    'common.premium': 'Byiza cyane',
    'common.viewAll': 'Reba Byose',
    'common.learnMore': 'Menya Byinshi',
    'common.getStarted': 'Tangira',
    'common.contactUs': 'Twandikire',
    'common.readMore': 'Soma Byinshi',
    'common.sortBy': 'Shiraho ukurikije',
    'common.filterBy': 'Shungura ukurikije',
    'common.search': 'Shakisha',
    'common.all': 'Byose',
    'common.category': 'Icyiciro',
    'common.categories': 'Ibyiciro',
    'common.name': 'Izina',
    'common.email': 'Imeyili',
    'common.phone': 'Telefoni',
    'common.message': 'Ubutumwa',
    'common.submit': 'Ohereza',
    'common.send': 'Ohereza',
    'common.close': 'Funga',
    'common.save': 'Bika',
    'common.cancel': 'Hagarika',
    'common.edit': 'Hindura',
    'common.delete': 'Siba',
    'common.update': 'Kuvugurura',
    'common.create': 'Kurema',
    'common.add': 'Ongeraho',
    'common.remove': 'Kuraho',
    'common.yes': 'Yego',
    'common.no': 'Oya',
    'common.ok': 'Sawa',
    
    // Home Page
    'home.hero.titleStart': 'Gukurikirana, Kubaza Inama, no',
    'home.hero.titleEnd': 'Kwita ku Matungo Yawe',
    'home.hero.subtitle': 'Ibisubizo bigezweho by\'abafite amatungo n\'inyamanswa zo mu rugo. Gukurikirana mu buryo bugezweho, kubaza inama inzobere, n\'ubuvuzi byuzuye - byose ahantu hamwe',
    'home.hero.cta': 'Reba Amaserivisi Yacu',
    'home.hero.bookConsultation': 'Fata Randevu',
    'home.hero.trusted': 'Byizerwemo n\'abafite inyamanswa barenga 5,000 muri Rwanda',
    'home.services.title': 'Amaserivisi Yacu Akomeye',
    'home.services.subtitle': 'Ibisubizo byuzuye by\'ubuzima bw\'amatungo, gukurikirana, n\'imicungire kugira ngo twemeze ubuzima bwiza bw\'amatungo yawe n\'inyamanswa zo mu rugo',
    'home.features.title': 'Impamvu wahitamo NTDM Animal Hospital?',
    'home.features.subtitle': 'Menya itandukaniro hamwe n\'ubwiyunge bwacu bwo gukora neza, ubuhanga, n\'ubuvuzi byuzuye bw\'inyamanswa',
    'home.features.expert.title': 'Abaganga b\'amatungo b\'Inzobere',
    'home.features.expert.desc': 'Itsinda ryacu ry\'abaganga b\'amatungo bemerewe rizana uburambe bw\'imyaka myinshi n\'ubumenyi bwihariye muri buri kibazo',
    'home.features.technology.title': 'Ikoranabuhanga Rigezweho',
    'home.features.technology.desc': 'Dukoresha ibikoresho bigezweho byo gukurikirana n\'ibikoresho byo gusuzuma kugira ngo dutange ubuvuzi bwiza ku matungo yawe',
    'home.features.comprehensive.title': 'Ubuvuzi Byuzuye',
    'home.features.comprehensive.desc': 'Kuva mu buvuzi bwo gukumira kugeza ku maserivisi y\'ubwiyunge, dutanga ibisubizo byuzuye by\'ibyo ukeneye byose ku matungo yawe',
    'home.testimonials.title': 'Icyo Abakiriya Bacu Bavuga',
    'home.testimonials.subtitle': 'Ntiwemere gusa ijambo ryacu. Dore icyo abafite amatungo muri Rwanda bavuga kuri NTDM Animal Hospital',
    'home.testimonials.farmer': 'Umworozi w\'Amatungo',
    'home.testimonials.petOwner': 'Nyir\'itungo ryo mu Rugo',
    'home.testimonials.poultryFarmer': 'Umworozi w\'Inkoko',
    'home.testimonials.dairyFarmer': 'Umworozi w\'Amata',
    'home.testimonials.quote1': 'Ibikoresho byo gukurikirana biva kuri NTDM byahinduye uburyo ncunga inka zanjye. Nshobora gukurikirana aho ziherereye n\'ubuzima bwazo mu gihe nyacyo, ibyo byongereye cyane umusaruro w\'ubworozi bwanjye',
    'home.testimonials.quote2': 'Inama za tekinoroji ni byoroshye cyane. Igihe imbwa yanjye yarwariye, nabonye inama z\'inzobere mu minota mike nta kugenda kwa muganga. Ndasaba cyane!',
    'home.testimonials.quote3': 'Sisitemu yo gukurikirana indwara yantumye nkagaragaza vuba indwara mu bworozi bwanjye bw\'inkoko. Igisubizo cyihuse cy\'abaganga b\'inyamanswa ba NTDM cyarokoje inkoko nyinshi. Serivisi yabo ni nziza cyane',
    'home.testimonials.quote4': 'Naguze inka z\'amata binyuze mu isoko rya NTDM maze mbona amatungo asanzwe kandi zitanga amata menshi. Ubufasha bwabo bwo gukurikirana n\'ubushyigikire byari bitangaje. Umusaruro w\'amata wanjye wiyongereye 30%!',
    'home.cta.title': 'Witeguye Kubona Ubuvuzi Bwiza bw\'Amatungo?',
    'home.cta.subtitle': 'Teganya inama yawe uyu munsi kandi ureke abaganga bacu b\'inzobere b\'amatungo bagufashe kubungabunga ubuzima bwiza n\'umusaruro w\'amatungo zawe',
    'home.cta.button': 'Teganya Inama Yawe Ubu',
    'home.locations.title': 'Aho Duherereye',
    'home.locations.subtitle': 'Dusure ku mwe mu bigo byacu byoroshye biri mu Rwanda. Buri bitaro gitanga serivisi zacu zose z\'ubuvuzi bw\'amatungo',
    'home.locations.directions': 'Reba Icyerekezo',
    
    // Portal Section
    'home.portal.title': 'Urubuga rw\'Abakiriya',
    'home.portal.subtitle': 'Urubuga rwacu rwuzuye rw\'abakiriya ruguhera ubushobozi bwuzuye bwo kugenzura ubuzima n\'imicungire y\'amatungo zawe. Gukurikirana, kubaza inama, no kwita ku nyamaswa zawe byoroshye',
    'home.portal.management.title': 'Imicungire y\'Amatungo',
    'home.portal.management.desc': 'Kwandikisha no gukurikirana amatungo yawe yose ahantu hamwe hamwe n\'amakuru arambuye y\'ubuzima n\'amakuru y\'aho ziherereye',
    'home.portal.consultations.title': 'Inama z\'Ubuvuzi',
    'home.portal.consultations.desc': 'Teganya kandi ucunge inama za tekinoroji n\'abaganga bacu b\'inzobere b\'amatungo uhereye hose',
    'home.portal.alerts.title': 'Amakuru y\'Ako Kanya',
    'home.portal.alerts.desc': 'Akira amakuru y\'ako kanya yerekeye ubuzima bw\'amatungo yawe, impinduka z\'aho ziherereye, cyangwa kwibutsa gahunda',
    'home.portal.records.title': 'Inyandiko z\'Ubuzima',
    'home.portal.records.desc': 'Gera ku mateka yuzuye y\'ubuvuzi, imiti, n\'igenamigambi ry\'ubuvuzi bw\'amatungo yawe zose zanditswe',
    'home.portal.login': 'Injira ku Rubuga',
    'home.portal.createAccount': 'Fungura Konti',
    'home.portal.trackTitle': 'Kurikirana Amatungo Yawe Hose',
    'home.portal.trackDesc': 'Gera ku makuru y\'ako kanya n\'amakuru y\'ubuzima uhereye kuri terefone yawe cyangwa mudasobwa',
    
    // Services
    'services.title': 'Amaserivisi Yacu',
    'services.subtitle': 'Ibisubizo byuzuye by\'ubuvuzi n\'imicungire y\'inyamanswa',
    'services.tracking.title': 'Gukurikirana inyamanswa',
    'services.tracking.desc': 'Ibikoresho bya GPS bigezweho byo gukurikirana amatungo',
    'services.consultation.title': 'Inama z\'Ubuvuzi',
    'services.consultation.desc': 'Inama n\'ubuvuzi bw\'ireme bw\'inyamanswa',
    'services.monitoring.title': 'Gukurikirana Indwara',
    'services.monitoring.desc': 'Kumenya hakiri kare no gukumira indwara z\'inyamanswa',
    
    // Pharmacy
    'pharmacy.title': 'Farumasi y\'amatungo',
    'pharmacy.subtitle': 'Imiti n\'ibikoresho by\'ubuvuzi bw\'amatungo',
    'pharmacy.notFound': 'Umuti ntubonetse',
    'pharmacy.notFoundDesc': 'Umuti ushaka ntuhari.',
    'pharmacy.dosage': 'Ingano y\'Umuti',
    'pharmacy.sideEffects': 'Ingaruka Mbi',
    'pharmacy.instructions': 'Amabwiriza',
    'pharmacy.prescription': 'Icyemezo cy\'Umuganga Gikenewe',
    
    // Animal Sales
    'animals.title': 'Amatungo Meza',
    'animals.subtitle': 'amatungo asanzwe kandi zifite ubuzima bwiza',
    'animals.notFound': 'Amatungo ntabonetse',
    'animals.notFoundDesc': 'amatungo ushaka ntahari.',
    'animals.breed': 'Ubwoko',
    'animals.age': 'Imyaka',
    'animals.weight': 'Uburemere',
    'animals.health': 'Ubuzima',
    'animals.vaccination': 'Urukingo',
    'animals.gender': 'Igitsina',
    
    // Feeds
    'feeds.title': 'Indyo Nziza z\'amatungo',
    'feeds.subtitle': 'Indyo nziza z\'amatungo zisanzwe kandi zibyara byinshi',
    'feeds.notFound': 'Indyo ntizibonetse',
    'feeds.notFoundDesc': 'Indyo ushaka ntizihari.',
    'feeds.feedDetails': 'Ibisobanuro by\'Indyo',
    'feeds.type': 'Ubwoko',
    'feeds.quality': 'Ubwiza',
    'feeds.targetAnimal': 'amatungo agenewe',
    'feeds.package': 'Ipaki',
    'feeds.availability': 'Kuboneka',
    'feeds.status': 'Uko bimeze',
    'feeds.qualityRating': 'Igipimo cy\'Ubwiza',
    'feeds.nutritionFacts': 'Amakuru y\'Intungamubiri',
    'feeds.ingredients': 'Ibigize',
    
    // About
    'about.title': 'Ibibazo kuri NTDM Animal Hospital',
    'about.subtitle': 'Ikigo gikomeye cy\'ubuvuzi bw\'inyamanswa mu Rwanda',
    'about.mission': 'Intego Yacu',
    'about.vision': 'Icyerekezo Cyacu',
    'about.values': 'Indangagaciro Zacu',
    'about.team': 'Itsinda Ryacu',
    'about.history': 'Amateka Yacu',
    'about.mentor': 'Abajyanama Bacu',
    'about.experience': 'Menya Itandukaniro rya NTDM',
    'about.experienceParagraph': 'Turagutumiye mu gusura ibitaro by’amatungo bya NTDM no kwibonera ibyo twiyemeje ku buzima bw’amatungo, guhanga udushya, naserivisi idasanzwe.',
    
    // Contact
    'contact.title': 'Twandikire',
    'contact.subtitle': 'Turi hano kugira ngo tusubize ibibazo byose ushobora kugira ku maserivisi yacu cyangwa kugira ngo uteganye inama yawe ikurikira',
    'contact.address': 'Aderesi',
    'contact.hours': 'Amasaha y\'Akazi',
    'contact.emergency': 'Guhamagara mu Byihutirwa',
    'contact.form.title': 'Twoherereze ubutumwa',
    'contact.form.success': 'Ubutumwa Bwoherejwe!',
    'contact.form.error': 'Byanze kohereza ubutumwa. Ongera ugerageze.',
    'contact.form.thankYou': 'Murakoze kutuvugana. Tuzabasubiza vuba bishoboka',
    'contact.form.sendAnother': 'Ohereza Ubundi Butumwa',
    'contact.form.namePlaceholder': 'Injiza amazina yawe yose',
    'contact.form.emailPlaceholder': 'Injiza aderesi ya imeyili yawe',
    'contact.form.phonePlaceholder': 'Injiza nimero ya telefoni yawe',
    'contact.form.messagePlaceholder': 'Injiza ubutumwa bwawe',
    'contact.form.sending': 'Biroherezwa...',
    'contact.findUs': 'Dusange',
    'contact.getInTouch': 'Twandikire',
    'common.today': 'Uyu Munsi',
    
    // Footer
    'footer.company': 'NTDM Animal Hospital',
    'footer.description': 'Guhindura ubuzima bw\'inyamanswa hakoreshejwe tekinoroji igezweho yo gukurikirana, kubaza inama, n\'ubuvuzi bw\'amatungo n\'inyamanswa zo mu rugo',
    'footer.quickLinks': 'Ihuza Ryihuse',
    'footer.services': 'Amaserivisi',
    'footer.contact': 'Amakuru yo Kuvugana',
    'footer.followUs': 'Dukurikire',
    'footer.rights': 'Uburenganzira bwose burarinzwe',
    'footer.weekdays': 'Kuwa mbere - Kuwa gatanu',
    'footer.saturday': 'Kuwa gatandatu',
    'footer.newsletter': 'Iyandikishe Mu kanyamakuru Kacu',
    'footer.newsletterDesc': 'Komeza ukurikirana amaserivisi yacu mashya, inama zo kwita ku nyamanswa, n\'amakuru y\'ibihe',
    'footer.emailPlaceholder': 'Injiza imeyili yawe',
    'footer.subscribe': 'Iyandikishe',
    'footer.serving': 'Dukora mu Rwanda no mu Burasirazuba bwa Afurika',
    'footer.tagline': 'Gukurikirana, Kubaza Inama, no Kwita ku Matungo Yawe',
    'Book Consultation': 'Fata randevu',
    'Customer Portal': 'Urubuga rw\'Abakiriya',
    
    // Blog
    'blog.subtitle': 'Ubumenyi bw\'inzobere, inama, n\'amakuru yerekeye ubuzima bw\'amatungo, gukurikirana, no kwita ku nyamaswa biva ku baganga bacu b\'amatungo',
    
    // Booking
    'booking.title': 'Teganya Inama Yawe',
    'booking.subtitle': 'Teganya gusura NTDM Animal Hospital kandi umenye amaserivisi yacu y\'ubuvuzi bw\'amatungo',
    
    // Sorting & Filtering
    'sort.newest': 'Bishya Mbere',
    'sort.oldest': 'Bya Kera Mbere',
    'sort.priceHigh': 'Igiciro: Kinini kugeza Gito',
    'sort.priceLow': 'Igiciro: Gito kugeza Kinini',
    'sort.nameAZ': 'Izina: A kugeza Z',
    'sort.nameZA': 'Izina: Z kugeza A',
    
    // Quality levels
    'quality.high': 'Ubwiza Bukomeye',
    'quality.medium': 'Ubwiza Bwo Hagati',
    'quality.low': 'Ubwiza Buke',
    'quality.premium': 'Ubwiza bw\'Ireme',
    
    // Auth
    'auth.loginDesc': 'Injiza amakuru yawe kugira ngo ubone konti yawe',
    'auth.password': 'Ijambo Ryibanga',
    'auth.emailPlaceholder': 'Injiza imeyili yawe',
    'auth.passwordPlaceholder': 'Injiza ijambo ryibanga',
    'auth.loggingIn': 'Kwinjira...',
    'auth.noAccount': 'Nta konti ufite?',
    'auth.registerHere': 'Iyandikishe hano',
    'auth.accountCreated': 'Konti Yaremwe Neza!',
    'auth.welcome': 'Murakaza neza kuri NTDM Animal Hospital',
    'auth.checkEmail': 'Nyamuneka reba mu meyili yawe ubone ubutumwa bwo kwakira',
    'auth.checkEmailTitle': 'Reba Imeyili Yawe',
    'auth.continueLogin': 'Komeza Kwinjira',
    'auth.createAccount': 'Fungura konti',
    'auth.createAccountDesc': 'Injiza amakuru yawe kugira ngo ufungure konti',
    'auth.confirmPassword': 'Emeza Ijambo Ryibanga',
    'auth.accountType': 'Ubwoko bwa Konti',
    'auth.farmerPetOwner': 'Umworozi',
    'auth.creatingAccount': 'Gufungura konti...',
    'auth.haveAccount': 'Usanzwe ufite konti?',
    'auth.signIn': 'Injira',
    'auth.welcomeBack': 'Murakaza Neza Nanone kuri NTDM Animal Hospital',
    'auth.loginWelcomeDesc': 'Injira kugira ngo ubone dashboard yawe, ukurikire amatungo zawe, kandi ucunge inama zawe',
    'auth.joinNTDM': 'Jya muri NTDM Animal Hospital',
    'auth.registerWelcomeDesc': 'Fungura konti kugira ngo ubone serivisi zacu, ukurikire amatungo yawe, kandi ucunge inama zawe',
    'auth.sector': 'Umurenge',
    'auth.district': 'Akarere',
    'auth.orContinueWith': 'Komeza na',
    'auth.phoneNumber': 'Nimero ya Telefoni',

    // Farmer Dashboard
    'farmer.dashboard': 'Ikibaho cy\'Umworozi',
    'farmer.welcomeBack': 'Murakaza neza',
    'farmer.manageFarm': 'Genzura ubworozi bwawe neza ukoresheje ibikoresho byacu byuzuye',
    'farmer.animals': 'Amatungo',
    'farmer.registered': 'Byanditswe',
    'farmer.pending': 'Bitegereje',
    'farmer.awaiting': 'Bitegereje',
    'farmer.accepted': 'Byemewe',
    'farmer.confirmed': 'Byemejwe',
    'farmer.rejected': 'Byanze',
    'farmer.declined': 'Byanze',
    'farmer.registerAnimal': 'Andika Itungo',
    'farmer.addNewLivestock': 'Ongeraho itungo rishya',
    'farmer.bookConsultation': 'Gena Inama',
    'farmer.scheduleVisit': 'Gena gusura',
    'farmer.viewConsultations': 'Reba Inama',
    'farmer.manageBookings': 'Genzura amabwiriza',
    'farmer.recentActivity': 'Ibikorwa bya Vuba',
    'farmer.items': 'ibintu',
    'farmer.animalRegistered': 'Itungo ryanditswe',
    'farmer.addedOn': 'Yongerwemo ku',
    'farmer.consultation': 'inama',
    'farmer.bookedOn': 'Yagenewe ku',
    'farmer.noRecentActivity': 'Nta bikorwa bya vuba',
    'farmer.farmActivitiesAppear': 'Ibikorwa by\'ubworozi bwawe bizagaragara hano',
    'farmer.portal': 'Urubuga rw\'Umworozi',
    'farmer.dashboard': 'Ikibaho',
    'farmer.consultations': 'Inama',
    'farmer.tracking': 'Gukurikirana',
    'farmer.messages': 'Ubutumwa',
    'farmer.notifications': 'Imenyesha',
    'farmer.profile': 'Umwirondoro',
    'farmer.settings': 'Amagenamiterere',
    'farmer.logout': 'Gusohoka',
    'farmer.myAnimals': 'Amatungo Yanjye',
    'farmer.registeredAnimals': 'Amatungo Yanditswe',
    'farmer.registerNewAnimal': 'Andika Itungo Rishya',
    'farmer.animalsInventory': 'Urutonde rw\'amatungo',
    'farmer.noAnimalsYet': 'Ntufite amatungo yanditswe',
    'farmer.registerAnAnimal': 'Andika Itungo',
    'farmer.name': 'Izina',
    'farmer.type': 'Ubwoko',
    'farmer.breed': 'Ubwoko bw\'Itungo',
    'farmer.location': 'Aho iherereye',
    'farmer.status': 'Uko imeze',
    'farmer.price': 'Igiciro',
    'farmer.actions': 'Ibikorwa',
    'farmer.healthy': 'Ifite ubuzima bwiza',
    'farmer.sick': 'Irwaye',
    'farmer.underTreatment': 'Iravurwa',
    'farmer.viewDetails': 'Reba Amakuru',
    'farmer.edit': 'Hindura',
    'farmer.myConsultations': 'Inama Zanjye',
    'farmer.newConsultation': 'Inama Nshya',
    'farmer.consultationHistory': 'Amateka y\'Inama',
    'farmer.noConsultationsYet': 'Ntufite inama',
    'farmer.bookAConsultation': 'Gena Inama',
    'farmer.service': 'Serivisi',
    'farmer.doctor': 'Muganga',
    'farmer.date': 'Itariki',
    'farmer.time': 'Igihe',
    'farmer.delete': 'Gusiba',
    'farmer.myProfile': 'Umwirondoro Wanjye',
    'farmer.farmer': 'Umworozi',
    'farmer.fullName': 'Amazina Yose',
    'farmer.bio': 'Incamake',
    'farmer.animalInformation': 'Amakuru y\'itungo',
    'farmer.enterAnimalName': 'Andika izina ry\'itungo',
    'farmer.animalType': 'Ubwoko bw\'itungo',
    'farmer.selectAnimalType': 'Hitamo ubwoko bw\'itungo',
    'farmer.cow': 'Inka',
    'farmer.goat': 'Ihene',
    'farmer.sheep': 'Intama',
    'farmer.chicken': 'Inkoko',
    'farmer.dog': 'Imbwa',
    'farmer.cat': 'Injangwe',
    'farmer.other': 'Ikindi',
    'farmer.enterBreed': 'Andika ubwoko',
    'farmer.class': 'Icyiciro',
    'farmer.selectClass': 'Hitamo icyiciro',
    'farmer.dairy': 'Amata',
    'farmer.meat': 'Inyama',
    'farmer.poultry': 'Inkoko',
    'farmer.pet': 'Itungo ryo mu rugo',
    'farmer.district': 'Akarere',
    'farmer.selectDistrict': 'Hitamo akarere',
    'farmer.sector': 'Umurenge',
    'farmer.selectSector': 'Hitamo umurenge',
    'farmer.ownerName': 'Izina ry\'Umunyangabo',
    'farmer.enterOwnerName': 'Andika izina ry\'umunyangabo',
    'farmer.phoneNumber': 'Nimero ya Telefoni',
    'farmer.enterPhoneNumber': 'Andika nimero ya telefoni',
    'farmer.priceRWF': 'Igiciro (RWF)',
    'farmer.enterPrice': 'Andika igiciro',
    'farmer.cancel': 'Hagarika',
    'farmer.registering': 'Gukoresha...',
    'farmer.communicateVeterinarians': 'Ganira n\'abaganga b\'amatungo ku bijyanye n\'amatungo yawe',
    'farmer.searchMessages': 'Shakisha ubutumwa...',
    'farmer.startNewConversation': 'Tangira Ikiganiro Gishya',
    'farmer.noConversationsYet': 'Nta biganiro. Tangira ikiganiro gishya!',
    'farmer.noMessagesYet': 'Nta butumwa',
    'farmer.veterinarian': 'Muganga w\'Amatungo',
    'farmer.noMessagesStart': 'Nta butumwa. Tangira ikiganiro!',
    'farmer.typeMessage': 'Andika ubutumwa...',
    'farmer.selectConversation': 'Hitamo ikiganiro kugira ngo utangire kuganira',
    'farmer.cowHealthMonitor': 'Gukurikirana Ubuzima bw\'Inka',
    'farmer.realTimeTracking': 'Gukurikirana ubuzima n\'aho iherereye mu gihe nyacyo',
    'farmer.lastUpdated': 'Byavuguruwe bwa nyuma',
    'farmer.exportReport': 'Kohereza Raporo',
    'farmer.refresh': 'Kuvugurura',
    'farmer.dataSourceConfig': 'Gushyiraho Inkomoko y\'Amakuru',
    'farmer.channelId': 'ID y\'Umuyoboro',
    'farmer.apiKey': 'Urufunguzo rwa API',
    'farmer.resultsCount': 'Umubare w\'Ibisubizo',
    'farmer.fetch': 'Gukuramo',
    'farmer.loadingSensorData': 'Gupakurura amakuru y\'ibikoresho...',
    'farmer.noDataAvailable': 'Nta makuru aboneka',
    'farmer.noSensorData': 'Nta makuru y\'ibikoresho yabonetse ku muyoboro wahiswemo. Nyamuneka menya Channel ID na API Key.',
    'farmer.tryAgain': 'Ongera ugerageze',
    'farmer.dataFieldsMapping': 'Gushyiraho Imiterere y\'Amakuru',
    'farmer.field': 'Umurongo',
    'farmer.latest': 'Bya Vuba',
    'farmer.average': 'Impuzandengo',
    'farmer.locationCoverage': 'Gukurikirana Aho Iherereye',
    'farmer.healthMetricsTrend': 'Ihindagurika ry\'Ubuzima',
    'farmer.distribution': 'Ikwirakwizwa',
    'farmer.locationTrackingInRwanda': 'Gukurikirana Aho Iherereye mu Rwanda',
    'farmer.recentReadings': 'Amakuru ya Vuba',
    'farmer.time': 'Igihe',
    'farmer.status': 'Uko Bimeze',
    'farmer.location': 'Aho Biherereye',
    'farmer.noLocationData': 'Nta makuru y\'aho biherereye',
    'farmer.healthStatusDistribution': 'Ikwirakwizwa ry\'Ubuzima',
    'farmer.bpmRangeDistribution': 'Ikwirakwizwa rya BPM',
    'farmer.noDataAvailableChart': 'Nta makuru aboneka',
    'farmer.count': 'Umubare',
    'farmer.readings': 'amakuru',
    'farmer.ofTotal': 'muri rusange',
    'farmer.animalHealthMonitoringReport': 'Raporo k\'ubuzima bw\'itungo',
    'farmer.animal': 'Itungo',
    'farmer.generated': 'Byakozwe',
    'farmer.healthSummary': 'Incamake y\'Ubuzima',
    'farmer.temperature': 'Ubushyuhe',
    'farmer.timestamp': 'Igihe',
    'farmer.latitude': 'Latitude',
    'farmer.longitude': 'Longitude',
    'farmer.bpmStatus': 'Uko BPM Imeze',
    'farmer.tempStatus': 'Uko Ubushyuhe Bumeze',
    'farmer.hasLocation': 'Ifite Aho Iherereye',
    'farmer.animalInfo': 'Amakuru y\'Itungo',
    'farmer.healthData': 'Amakuru y\'Ubuzima',
    'farmer.reportDate': 'Itariki ya Raporo',
    'farmer.totalRecords': 'Amakuru Yose',
    'farmer.unknown': 'Bitazwi',
    'farmer.yes': 'Yego',
    'farmer.no': 'Oya',
    'farmer.noData': 'Nta makuru',
    'farmer.low': 'Bike',
    'farmer.normal': 'Bisanzwe',
    'farmer.elevated': 'Byiyongereye',
    'farmer.high': 'Byinshi',
    'farmer.consultationDetails': 'Amakuru y\'Inama',
    'farmer.backToAllConsultations': 'Subira ku Nama Zose',
    'farmer.consultationFor': 'Inama y\'inkingo',
    'farmer.acceptedWithFeedback': 'Yemewe hamwe n\'igitekerezo',
    'farmer.rejectedWithFeedback': 'Yanze hamwe n\'igitekerezo',
    'farmer.completedWithFeedback': 'Yarangiye hamwe n\'igitekerezo',
    'farmer.fullName': 'Amazina Yose',
    'farmer.unknownDoctor': 'Muganga Utazwi',
    'farmer.createdAt': 'Byakozwe',
    'farmer.editConsultation': 'Hindura Inama',
    'farmer.deleteConsultation': 'Siba Inama',
    'farmer.locationPointsTracked': 'ahantu hakurikiranwa',
    'farmer.lastSeen': 'Yabonetse bwa nyuma',
    'farmer.resetView': 'Subiza Isura',
    'farmer.latestLocation': 'Aho Iherereye Vuba',
    'farmer.loadingRwandaMap': 'Gupakurura ikarita ya Rwanda...',
    'farmer.coverageArea': 'Agace Gakurikiranwa',
    'farmer.trackingLocations': 'Gukurikirana ahantu',
    'farmer.currentHealth': 'Ubuzima Bwa Vuba',
    'farmer.heartRate': 'Umuvuduko w\'umutima',
    'farmer.bodyTemperature': 'Ubushyuhe bw\'umubiri',
    'farmer.selectedLocationDetails': 'Amakuru y\'Ahantu Hahiswemo',
    'farmer.coordinates': 'Ibipimo',
    'farmer.multiplePoints': 'Byinshi',
    'farmer.singlePoint': 'Kimwe',
    'farmer.noPoints': 'Nta na kimwe',
    
    // Animal Details
    'animal.details': 'Amakuru y\'Itungo',
    'animal.backToAnimals': 'Subira k\'umatungo',
    'animal.breed': 'Ubwoko',
    'animal.class': 'Icyiciro',
    'animal.location': 'Aho iherereye',
    'animal.price': 'Igiciro',
    'animal.owner': 'Nyir\'ubwite',
    'animal.phone': 'Telefoni',
    'animal.registeredOn': 'Yanditswe ku wa',
    'animal.deleteAnimal': 'Gusiba Itungo',
    'animal.editAnimal': 'Guhindura Amakuru',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'en' || saved === 'rw')) {
      setLanguage(saved)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}